[김수정]Westagram Backend Project - Express 초기 환경세팅
wecode-bootcamp-korea/39-backend-westagram-2 pull request #10
Opened 2022-11-03 04:29 UTC by Kimsu10

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-11-03 06:44 UTC, SeongJoon-K requested changes
.vscode 디렉토리와 schema.sql, practice.js와 같은 파일은 github 상에 올라오지 않도록
gitignore에 작성해서 올라오지 않도록 수정해 주세요 !

2022-11-03 06:44 UTC, SeongJoon-K commented on sujeong/app.js
> +
개발 시 작성한 주석은 제거해 주세요 !
```suggestion
```

2022-11-03 06:44 UTC, SeongJoon-K commented on sujeong/app.js
> +
dotenv는 최상단에 아래와 같이 작성하여 수정해 주세요 !
```suggestion
require('dotenv').config() 
```

2022-11-03 06:44 UTC, SeongJoon-K commented on sujeong/app.js
> +})
- myDataSource 보다는 `appDataSource` , `mysqlDataSource` 혹은 간결하게 `database`로 변수명을 변경해주세요. “my”라는 용어는 예제 코드에서는 사용할 수 있으나 실제 코드에서는 피해주세요.

2022-11-03 06:44 UTC, SeongJoon-K commented on sujeong/package.json
> +}
express의 경우 해당 프로젝트를 사용하기 위해서 필수적으로 존재해야하는 패키지입니다. 그렇기에 devdependencies가 아닌 dependencies에 관리되어야 합니다 !

```suggestion
  "devDependencies": {
    "nodemon": "^2.0.20"
  },
  "dependencies": {
    "cors": "^2.8.5",
    "dbmate": "^1.0.3",
    "dotenv": "^16.0.3",
    "morgan": "^1.10.0",
    "mysql": "^2.18.1",
    "typeorm": "^0.3.10"
    "express": "^4.18.2",
  }
}
```

2022-11-03 10:01 UTC, SeongJoon-K approved these changes
수정님 ! 수고많으셨습니다 !

2022-11-03 10:02 UTC, SeongJoon-K requested changes
.vscode 파일 제거해 주세요 수정님 !

2022-11-03 12:45 UTC, Kimsu10 commented
> .vscode 파일 제거해 주세요 수정님 !
수정했습니다!

2022-11-04 01:18 UTC, SeongJoon-K requested changes
- schema.sql 파일이 현재 git 상에서 관리되고 있음. gitignore를 사용해 github 상에서 관리되지 않도록 해주세요 ! 🙏🏻
- app.js 파일 피드백 반영해주세요 !

assignment1 이 우선적으로 merge가 되지 않으면 다음 과제 merge가 불가능하니 참고 바랍니다 !

2022-11-04 01:18 UTC, SeongJoon-K commented on sujeong/app.js
> +const { runInNewContext } = require('vm');
```suggestion
require('dotenv').config();

const http = require('http');
const express = require('express');
const cors = require('cors');
const morgan = require('morgan');

const { DataSource } = require('typeorm');

```

`const { runInNewContext } = require('vm');` 해당 부분은 어디서 사용해서 호출하신걸까요?

2022-11-04 01:20 UTC, SeongJoon-K commented
더불어 PR명도 아래와 같이 수정해 주세요!
예시 ) [이름] Assignment 1: Express API -유저회원가입하기

2022-11-04 01:53 UTC, Kimsu10 commented on sujeong/app.js
> +const { runInNewContext } = require('vm');
영상보면서 하다가 들어간거같아요 지웠습니다!

2022-11-04 05:31 UTC, bigfanoftim requested changes

2022-11-04 05:31 UTC, bigfanoftim commented on sujeong/db/migrations/20221103234500_create_signup_table.sql
> +CREATE TABLE signup(
```suggestion
CREATE TABLE users (
```

2022-11-04 05:31 UTC, bigfanoftim commented on sujeong/db/migrations/20221103234500_create_signup_table.sql
> +    email VARCHAR(100) NOT NULL,
- 해당 컬럼은 중복되면 안되는 데이터를 저장하는 컬럼입니다. 따라서 unique contraint를 추가해주셔야 합니다.

2022-11-04 06:19 UTC, merged