Seho/assignment3
wecode-bootcamp-korea/39-backend-westagram-2 pull request #12
Opened 2022-11-03 07:12 UTC by hosose

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- westagram 게시글 등록 부터 좋아요 누르기 까지 기능 구현 및 체크 完
		 
## 수정 사항들 자세한 내용
- 게시글 등록하기
- 전체 게시글 조회하기
- 유저의 게시글 조회하기
- 게시글 수정하기
- 게시글 삭제하기
- 좋아요 누르기

## 기타 질문 및 특이 사항
- http 응답코드 학습을 통해 응답코드 별 의미 확인 
- http 메소드 중 delete에는 req.body 값이 들어가지 않는다는 사실 확인
- 구조분해 할당을 통해 body값 또는 parameter 값을 지정할 수 있다는 사실 확인
- async, await 및 promise 에 대한 이해 (조금 더 이해 必)
- query문을 변수지정하여 합체할 수 있다는 사실 확인
- postman을 통해 req.body의 key 값을 확실히 이해
- 사진 첨부
▶ 게시글 등록하기
![39기_백엔드_김세호_assign2_postup_table](https://user-images.githubusercontent.com/112751572/199664551-f8bbe121-2868-4337-8b14-831f8c3235f7.png)
![39기_백엔드_김세호_assign2_postup_postman](https://user-images.githubusercontent.com/112751572/199664561-b954a094-94a9-4038-b719-ec91a65faeb8.png)

▶ 전체 게시글 조회하기
![39기_백엔드_김세호_assign2_posts_postman](https://user-images.githubusercontent.com/112751572/199664586-f9fca3bd-f042-4126-b0b1-a84679e412ac.png)
![39기_백엔드_김세호_assign2_posts_table](https://user-images.githubusercontent.com/112751572/199664597-da9de016-747c-4825-96ad-6d47d9723230.png)

▶ 유저의 게시글 조회하기
![39기_백엔드_김세호_assign2_userpostlist_postman png](https://user-images.githubusercontent.com/112751572/199664614-12b8c8ac-adc2-4c84-993c-0a9fdba1a195.png)
![39기_백엔드_김세호_assign2_userpostlist_npm png](https://user-images.githubusercontent.com/112751572/199664636-82c4fd2c-9520-4339-a5c5-0a5c616b820c.png)

▶ 게시글 수정하기
![39기_백엔드_김세호_assign2_postpatch_postman png](https://user-images.githubusercontent.com/112751572/199664691-5b7a2eb9-700e-4232-839f-fc1c2e550f45.png)

▶ 게시글 삭제하기
![39기_백엔드_김세호_assign2_postdel_postman png](https://user-images.githubusercontent.com/112751572/199664705-443ca672-f664-488f-980d-ce8c2ff20470.png)

▶ 좋아요 누르기
![39기_백엔드_김세호_assign8_liekecreated_postman png](https://user-images.githubusercontent.com/112751572/199664714-0799c9e5-c290-438f-a7d1-af1303b6448c.png)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-11-03 07:14 UTC, hosose commented
7번째 과제 commit 에 response가 안된다고 했는데 알고 보니 응답코드 204로 진행해서 안되었습니다. 이제는 잘 됩니다!

2022-11-04 01:22 UTC, SeongJoon-K commented
세호님 앞선 과제 피드백을 우선적으로 반영해주세요! 더불어  PR명도 아래와 같이 수정해 주세요!
예시 ) `[이름] Assignment 2 : Express API -유저 회원가입`

2022-11-04 06:26 UTC, SeongJoon-K requested changes

2022-11-04 06:26 UTC, SeongJoon-K commented on Kimseho_assignment/app.js
>  const myDataSource = new DataSource({
myDataSource 보다는 appDataSource , mysqlDataSource 혹은 간결하게 database로 변수명을 변경해주세요. “my”라는 용어는 예제 코드에서는 사용할 수 있으나 실제 코드에서는 피해주세요.

2022-11-06 07:26 UTC, hosose commented
API 문서화 https://documenter.getpostman.com/view/24101014/2s8YYHL3Uw

2022-11-06 07:52 UTC, SeongJoon-K requested changes
세호님 ! 현재 세호님 위스타그램 디렉토리 상위에 있는 package.json 파일이 수정사항이 있는 상태입니다. 이 부분을 간과하고 merge 하게 된다면, 다른 분들의 파일에 있는 package.json에서 conflict가 발생합니다. 해당 부분 수정후 push 해 주세요 !

2022-11-06 07:52 UTC, SeongJoon-K commented on Kimseho_assignment/app.js
> +  `,
세호님 ! 해당부분을 쿼리문을 파싱이전상태로 돌려서 쿼리문을 작성해주세요 !

2022-11-06 12:19 UTC, hosose commented on Kimseho_assignment/app.js
> +  `,
다시 돌려야하는 이유가 무엇인가요? 보안상으로는 ?가 들어간 것이 더 뛰어나다고 알고 있어가지고요.

2022-11-06 12:21 UTC, hosose commented on Kimseho_assignment/app.js
> +  `,
저번에 query문 때문에 json 파일이 깨져서 나와 mysql2로 변경하였는데 package.json 내에서 mysql2 에서 mysql 로 수동으로 변경하면 되는 것일까요?

2022-11-06 12:32 UTC, hosose commented on Kimseho_assignment/app.js
> +  `,
성준님! 막연히 고쳐라는 말보다는 고쳐야하는 이유까지 친절하게 이야기해주시면 좋을 것 같습니다! 저희가 잘 알지 못하는 부분도 있기 때문에 설명이 필요합니다!

2022-11-07 05:46 UTC, SeongJoon-K approved these changes

2022-11-07 05:46 UTC, SeongJoon-K commented on Kimseho_assignment/app.js
> +    `,
- SQL 문법도 가독성 좋게 만들어주는 것이 중요합니다. 회사마다 컨벤션이 다르겠지만, 위코드에서는 아래와 같은 SQL 문법의 컨벤션을 정하고 있습니다.
- 지금은 위코드에서 사용하고 있는 컨벤션을 지켜서 문법을 작성해주세요. 하지만 이는 회사마다 다르기 때문에, 정답이 아님을 반드시 인지해주세요.
- SQL 포맷팅은 다음 처럼 통일하면 좋을거 같습니다.
```suggestion
    `UPDATE posts
      SET
          posting_title = ?,
          posting_content = ?,
          posting_imgUrl = ?
      WHERE id = ?`,
```

2022-11-07 05:47 UTC, SeongJoon-K commented
세호님 ! app.js 파일에서 conflict가 있어서 해당 부분 수정 후 다시 라벨 변경해주시면 감사하겠습니다 ~

2022-11-07 05:58 UTC, hosose commented
수정했습니다! 확인 부탁드립니다.

2022-11-07 06:49 UTC, merged