[김수정]Assignment2:ExpressAPI-유저회원가입
wecode-bootcamp-korea/39-backend-westagram-2 pull request #15
Opened 2022-11-04 08:33 UTC by Kimsu10

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-11-04 08:34 UTC, Kimsu10 commented
<img width="759" alt="Assignment2" src="https://user-images.githubusercontent.com/107941176/199928518-cbe04d07-5ebb-4684-9d79-be56aab34224.png">

2022-11-05 04:33 UTC, Kimsu10 commented
<img width="1503" alt="스크린샷 2022-11-05 오후 1 29 31" src="https://user-images.githubusercontent.com/107941176/200101174-7f415035-6fcd-4038-b2db-3802ad53df52.png">

2022-11-06 07:55 UTC, SeongJoon-K requested changes
수정님 ! 현재 github 상에서 schema.sql 파일이 관리되고  있습니다. 해당 부분 수정 후 라벨 변경해 주시면 감사하겠습니다!

2022-11-06 13:26 UTC, Kimsu10 commented
성준님!! 브랜치랑 메인 다 확인해 봤는데 shema.sql 이 안보입니다. 
제가 올린 사진에 schema.sql 글자가 회색인데 이게 안뜨게 된거 아닌가요?

2022-11-07 01:30 UTC, SeongJoon-K commented
수정님 ! .gitignore에 등록하시고 나서 캐시를 삭제하지 않으신 거 같습니다! 
`git rm  --cashed` 명령어를 사용하시고 다시 push 해 보시면 되실겁니다 !
- 기존에 gitignore에 등록되지 않았던 파일은 이미 추적이 되고있기 때문에 캐시 삭제가 필요합니다 !

2022-11-07 07:14 UTC, Kimsu10 commented
git rm --cashed 입력시 일치하는 파일이 없다고 뜨는데 되었을까요?

2022-11-08 00:56 UTC, SeongJoon-K commented
수정님 ! 현재 file changed 를 보시면 동근님 db migrations 파일이 업로드 되어 있습니다!
이 부분을 수정하지 않고, merge 하게되면 main에서 conflict가 발생할 수 있습니다. 로컬에서 해당 부분 관련해서 올라오지 않게 한 후 다시 push 해 주세요!

2022-11-08 00:57 UTC, SeongJoon-K commented
`git rm --cashed` 우선 캐쉬 파일 제거 명령어가 잘못입력되었습니다 수정님! 
- `git rm --cached`로 입력하신게 맞으시다면, 입력 후 다시 push 진행 하시면 됩니다 !

2022-11-09 00:58 UTC, SeongJoon-K approved these changes

2022-11-09 00:58 UTC, merged