[김한솔] westagram assignment 3~8
wecode-bootcamp-korea/39-backend-westagram-2 pull request #17
Opened 2022-11-07 06:00 UTC by lukas0306

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
assignment 3-8 기능 구현

		 
## 수정 사항들 자세한 내용
3-게시글 등록
4-전체 게시글 조회
5-유저의 게시글 조회
6-게시글 수정
7-게시글 삭제
8-좋아요 기능

## 기타 질문 및 특이 사항
.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-11-08 01:07 UTC, SeongJoon-K requested changes
한솔님, eslint파일 및 prettier 파일이 github상에서 관리되고 있습니다. 해당 부분은 개발 시 개인 플러그인에 따라 달리 적용될 수 있기 때문에, 이를 .gitignore에 관리되도록 수정해주세요.
git ignore 등록 후, 이미 올라와 있는 github상의 캐시를 삭제해야하기 때문에
`git rm -rf --cached` 명령어를 통해서 캐시를 삭제해 주세요 !

2022-11-08 01:07 UTC, SeongJoon-K commented on hansol/app.js
> +    [name, email, password]
한솔님 ! SQL 포맷팅시, 줄바꿈과 띄어쓰기를 같이 사용하게 되면, github상에서 아래와 같이 정렬되지 않은 형태로 보여지게 됩니다. 아래와 같이 수정한 후에 다시 push 해주세요!
```suggestion
    `INSERT INTO users(
              name,
              email,
              password
      ) VALUES (?, ?, ?);`,
    [name, email, password]
```

2022-11-08 01:07 UTC, SeongJoon-K commented on hansol/db/migrations/20221102080531_create_users.sql
> +);
한솔님, sql파일 관련하여, 쿼리문을 아래와 같이 수정해 주세요! 다른 파일들도 동일하게 수정 부탁드립니다 !
```suggestion
CREATE TABLE users (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,       
  email VARCHAR(200) NOT NULL,
  profile_image VARCHAR(1000) NULL,    
  password VARCHAR(200) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),        
  updated_at TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP           
); 
```

2022-11-08 07:51 UTC, lukas0306 commented
수정하고 다시 push 했습니다.

2022-11-10 01:19 UTC, SeongJoon-K approved these changes

2022-11-10 01:19 UTC, merged