[김수정] Assignment 3~5: 게시글 등록하기~유저의 게시글 조회하기
wecode-bootcamp-korea/39-backend-westagram-2 pull request #21
Opened 2022-11-09 02:23 UTC by Kimsu10

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-11-10 01:29 UTC, SeongJoon-K requested changes
수정님 너무 잘 해주셨습니다 ! 피드백 반영해서 다시 수정해 주시면 감사하겠습니다!~

2022-11-10 01:29 UTC, SeongJoon-K commented on sujeong/app.js
> +    });
수정님 ! 해당 GET 요청의 엔드포인트를 봤을 때, 어떠한 정보를 가져오는지 이해하기 어렵습니다
더불어 엔드포인트 설정시 '_' 언더바 사용을 자제해 주시고, 오전에 있는 RESTFUL API 세션을 들으신 다음 꼭 수정해 주시기 바랍니다 
- 해당하는 유저의 게시물을 모두 가져오는 엔드포인트의 경우
- `/posts/:userId`와 같이 엔드포인트만 봤을  때, 이게 어떤 역할을 하는 API인지 판단이 될 수 있게끔 고민해 보세요!
```suggestion
app.get('/posts/:userId', async(req, res)=>{
    
    await appDataSource.query(
    `SELECT
        u.id as userId,
        u.profile_image as userProfileImage,
        p.user_id as postingId,
        p.image_url as postingImageUrl,
        p.content as postingContent
    FROM users u
    INNER JOIN posts p ON u.id = p.user_id;
    `,(err, rows) => {
        res.status(200).json(rows);
    });
});
```

2022-11-12 08:36 UTC, SeongJoon-K requested changes
수정님 !! Json Array 를 사용하여 구현해주셨군요 !! 너무 잘 하셨습니다 !! 
현재 github상에서 동근님의 migration 파일이 업로드 되어 있는데 해당 부분을 해결 해주시면 merge 해 드리겠습니다 주말간 파이팅 입니다 !!

2022-11-13 11:32 UTC, SeongJoon-K requested changes

2022-11-13 11:32 UTC, SeongJoon-K commented on .gitignore
> +.vscode
수정님! 현재 main에 존재하는 gitignore 가 수정된 이력이 있습니다. main 브랜치의 파일과 비교해서 다시 push 해 주세요!
```suggestion
```

2022-11-13 11:32 UTC, SeongJoon-K commented on sujeong/app.js
> +    });
수정님 ! 해당 스코프에 문제가 없는 지 다시 확인 해주세요 ~!
```suggestion
    await appDataSource.query(
    `SELECT
        u.id as userId,
        u.profile_image as userProfileImage,
        p.user_id as postingId,
        p.image_url as postingImageUrl,
        p.content as postingContent
    FROM users u
    INNER JOIN posts p ON u.id = p.user_id;
    `,(err, rows) => {
        res.status(200).json(rows);
    });
```

2022-11-13 11:32 UTC, SeongJoon-K commented on sujeong/app.js
> +    });
```suggestion
app.get('/posts/:userId', async (req , res)=>{
    const {userId} = req.params
    
    try {
        const [result] = await appDataSource.query(
        `SELECT
            u.id userId,
            u.profile_image userProfileImage,
        JSON_ARRAYAGG(
            JSON_OBJECT(
            "postingId", p.id,
            "postingImageUrl", p.image_url,
            "postingContnet", p.content)  
        ) as postings
        FROM users u 
        JOIN posts p ON p.user_id = u.id
        WHERE u.id = ${userId}
        GROUP BY u.id`
        );
        return res.status(200).json({ data: result });
    } catch (err) {
        return res.status(409).json({ error: 'invalid input' });
    }
});
```

2022-11-13 11:32 UTC, SeongJoon-K commented on sujeong/app.js
> +
수정님 !  409 http status code는 서버 충돌이 발생함을 의미하는 코드입니다!
상황에 맞는 http status code를 다시 수정해 주세요!
```suggestion
    res.status(200).json({data: result});
    } catch (err) {
        return res.status(409).json({"message": "invalid input"})
    }
});

```

2022-11-14 06:06 UTC, Kimsu10 commented on sujeong/app.js
> +
401로 바궜습니다!

2022-11-15 02:07 UTC, Kimsu10 commented on sujeong/app.js
> +    });
네 잘 되요~

2022-11-15 09:12 UTC, merged