[김한솔] Assignment 1: Express API - 초기환경세팅
wecode-bootcamp-korea/39-backend-westagram-2 pull request #4
Opened 2022-11-02 05:35 UTC by lukas0306

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
express 초기 환경 설정
		 
## 수정 사항들 자세한 내용
express등의 모듈 설치 및 dotenv모듈을 통한 환경변수 설정 및 연결.

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-11-02 06:42 UTC, SeongJoon-K requested changes

2022-11-02 06:42 UTC, SeongJoon-K commented on hansol/app.js
> +
- mport 순서 컨벤션에 맞게 수정해주세요! 사소한 부분이라 놓치기 쉽지만 처음 코드를 작성할 때부터 신경쓰고 작성하게 되면 추후에 관리하기도 용이하며 가독성도 좋아집니다.
- 다음과 같은 순서로 import 해줍니다.
    - Bulit-in 패키지
    - 3rd-party 패키지
    - custom 패키지
```suggestion
//// Built-in package
const http = require('http')

//// 3rd-party package
require('dotenv').config();
const express = require('express');
const cors    = require('cors');
const morgan  = require('morgan');
const { DataSource } = require('typeorm');

//custom package
const api = require('./../api')

const app = express();
```

2022-11-02 06:42 UTC, SeongJoon-K commented on hansol/package.json
> +    "typeorm": "^0.3.10"
- 프로젝트에서 3rd-party 패키지를 설치해서 사용할 때에는 주의해야 될 사항이 있습니다.
- 해당 패키지가 production 레벨(사용자에게 배포)에서 사용될 패키지인지 local 개발용도로만 사용되는 패키지인지를 알고 있어야 합니다.
- express, mysql, typeorm, dotenv, cors와 같은 패키지는 사용자에게 서비스되는 코드에서는 반드시 포함되어야 하는 라이브러리이므로 package.json 내에 `dependencies`에 포함되어야 합니다.
- 하지만, nodemon과 같은 패키지는 로컬에서 개발할 때, 생산성을 위해서 사용하는 패키지입니다. 그렇기 때문에 이는 `devDependencies`에 추가 혹은 `global 환경`에 설치해서 사용할 수 있도록 만들어주세요.

2022-11-02 06:42 UTC, SeongJoon-K commented on hansol/app.js
> +dotenv.config()//환경변수를 사용하기 전에 놔야함 밑으로 가면 에러발생.
개발시 사용한 주석은 지워주세요 !
```suggestion
```

2022-11-02 06:42 UTC, SeongJoon-K commented on hansol/app.js
> +
- myDataSource 보다는 `appDataSource` , `mysqlDataSource` 혹은 간결하게 `database`로 변수명을 변경해주세요. “my”라는 용어는 예제 코드에서는 사용할 수 있으나 실제 코드에서는 피해주세요.
- `DataSource.initialize()` 함수가 실행되고 나면, then()과 catch()를 사용해서 에러를 핸들링해줄 수 있습니다. 이렇게 하면, initialize() 함수가 실행되어서 database와 실제로 connection을 생성할 때, 성공했는지 실패했는지 여부를 확인할 수 있습니다.
- 추후 에러 핸들링을 담을 때의 가독성 및 확장성 보장을 위해 ".then"을 (typeorm datasource 공식문서에서 제안하는 것 처럼) 한칸 아래로 띄는 것을 권장드립니다.
- 참고 링크: [https://typeorm.biunav.com/en/data-source.html#what-is-datasource](https://typeorm.biunav.com/en/data-source.html#what-is-datasource)

2022-11-02 07:55 UTC, lukas0306 commented
수정했습니다.

2022-11-02 08:09 UTC, SeongJoon-K requested changes
해당 부분 수정 후 다시 push 후 라벨 변경해 주세요 !

2022-11-02 08:09 UTC, SeongJoon-K commented on hansol/app.js
> +dotenv.config()
```suggestion
require('dotenv').config()

const http = require('http')
const express = require('express')
const morgan = require('morgan')
const cors = require('cors')
const { DataSource } = require('typeorm')


const app = express()
const server = http.createServer(app)
const PORT = process.env.PORT;
```

2022-11-02 08:09 UTC, SeongJoon-K commented on hansol/app.js
> +    })
- myDataSource 보다는 `appDataSource` , `mysqlDataSource` 혹은 간결하게 `database`로 변수명을 변경해주세요. “my”라는 용어는 예제 코드에서는 사용할 수 있으나 실제 코드에서는 피해주세요.
- `DataSource.initialize()` 함수가 실행되고 나면, then()과 catch()를 사용해서 에러를 핸들링해줄 수 있습니다. 이렇게 하면, initialize() 함수가 실행되어서 database와 실제로 connection을 생성할 때, 성공했는지 실패했는지 여부를 확인할 수 있습니다.

2022-11-03 06:57 UTC, SeongJoon-K approved these changes

2022-11-03 06:57 UTC, merged